### ISSUE TITLE
incomplete release of hash elements

### ISSUE THREAD

**Issue by Domi17423** [brablc/postfix-tools#2]
Hello,

I just used this for some logs handling. Simple and effective. Thanks.

I ran into an easily corrected issue:
- in checkMatch, "quids" are released from the hash with an undef
- this releases the value but not the key
- leading to a memory leak problematic with huge logs
- better use "delete $P{$q};" which also releases the key and thus keeps the hash small

Regards,

**Comment by brablc** [comment]
Thanks for tip. Fixed in 98805aea5f727c6c13640002bf73d651522b836f.
